// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SipintarBeltim.Data;

#nullable disable

namespace SipintarBeltim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525030539_AddForumKomunikasi")]
    partial class AddForumKomunikasi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SipintarBeltim.Models.Aspek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Aspeks");
                });

            modelBuilder.Entity("SipintarBeltim.Models.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumArahan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForumTopikId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstansiTujuan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioritas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForumTopikId");

                    b.ToTable("ForumArahans");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumKomentar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ForumTopikId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForumTopikId");

                    b.ToTable("ForumKomentars");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumPengumuman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioritas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumPengumumans");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumTindakLanjut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ForumArahanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TanggalSelesai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForumArahanId");

                    b.ToTable("ForumTindakLanjuts");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumTopik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KewaspadaanDiniId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PeristiwaKonflikId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioritas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumTopiks");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Instansi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Instansis");
                });

            modelBuilder.Entity("SipintarBeltim.Models.JenisKonflik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JenisKonfliks");
                });

            modelBuilder.Entity("SipintarBeltim.Models.KewaspadaanDini", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatDetail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aspek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuktiFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatatanApproval")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gangguan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hambatan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KemungkinanAncamanDeskripsi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KemungkinanAncamanLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Periode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrediksiDampakDeskripsi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrediksiDampakLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rekomendasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SumberInformasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tantangan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TingkatRisiko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitikKoordinat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KewaspadaanDinis");
                });

            modelBuilder.Entity("SipintarBeltim.Models.LevelDampak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Skor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Skor")
                        .IsUnique();

                    b.ToTable("LevelDampaks");
                });

            modelBuilder.Entity("SipintarBeltim.Models.LevelKemungkinan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Skor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Skor")
                        .IsUnique();

                    b.ToTable("LevelKemungkinans");
                });

            modelBuilder.Entity("SipintarBeltim.Models.LevelRisiko", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkorMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkorMin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LevelRisikos");
                });

            modelBuilder.Entity("SipintarBeltim.Models.MatriksRisiko", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DampakId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KemungkinanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LevelRisikoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DampakId");

                    b.HasIndex("LevelRisikoId");

                    b.HasIndex("KemungkinanId", "DampakId")
                        .IsUnique();

                    b.ToTable("MatriksRisikos");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModulId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModulId");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Modul", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moduls");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Pelanggan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoTelp")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomorSambungan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pelanggan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            Alamat = "Jl. Merdeka No. 1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nama = "Ahmad Sudirman",
                            NomorSambungan = "001-001"
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            Alamat = "Jl. Pahlawan No. 5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nama = "Siti Rahayu",
                            NomorSambungan = "001-002"
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            Alamat = "Jl. Kartini No. 12",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nama = "Budi Santoso",
                            NomorSambungan = "002-001"
                        });
                });

            modelBuilder.Entity("SipintarBeltim.Models.PeristiwaKonflik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatDetail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuktiFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatatanApproval")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeskripsiAkibatPeristiwa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KerugianMateril")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keterangan")
                        .HasColumnType("TEXT");

                    b.Property<int>("KorbanKritis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KorbanLukaLuka")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KorbanMengungsi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatarBelakangKejadian")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPeristiwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Periode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaranTindakLanjut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SumberInformasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SumberSebabKonflik")
                        .HasColumnType("TEXT");

                    b.Property<string>("TingkatRisiko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitikKoordinat")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpayaPemulihan")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpayaPenanganan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PeristiwaKonfliks");
                });

            modelBuilder.Entity("SipintarBeltim.Models.PotensiKonflik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatDetail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aspek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuktiFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatatanApproval")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DampakDeskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DampakLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Desa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KemungkinanDeskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KemungkinanLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeteranganDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatarBelakangMasalah")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPotensiKonflik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Periode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rekomendasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SumberInformasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SumberSebabPermasalahan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TingkatRisiko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitikKoordinat")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpayaPenanganan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PotensiKonfliks");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SipintarBeltim.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanView")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("SipintarBeltim.Models.TenagaKerjaAsing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatDetail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatatanApproval")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JabatanKeterampilan")
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisIzinTinggal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keterangan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kewarganegaraan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPerusahaan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaTKA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoPaspor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoTelepon")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomorIMTA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Periode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaranTindakLanjut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SumberInformasi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TanggalBerakhirIMTA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TanggalMulaiIMTA")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitikKoordinat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TenagaKerjaAsings");
                });

            modelBuilder.Entity("SipintarBeltim.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SipintarBeltim.Models.WargaNegaraAsing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatDetail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatatanApproval")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisVisa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keterangan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kewarganegaraan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LamaTinggal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MasaBerlakuVisa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoPaspor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pekerjaan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Periode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaranTindakLanjut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sponsor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusTinggal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SumberInformasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitikKoordinat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WargaNegaraAsings");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Wilayah", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KodeBps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KodeBps")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Wilayahs");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumArahan", b =>
                {
                    b.HasOne("SipintarBeltim.Models.ForumTopik", "ForumTopik")
                        .WithMany()
                        .HasForeignKey("ForumTopikId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ForumTopik");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumKomentar", b =>
                {
                    b.HasOne("SipintarBeltim.Models.ForumTopik", "ForumTopik")
                        .WithMany("Komentars")
                        .HasForeignKey("ForumTopikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumTopik");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumTindakLanjut", b =>
                {
                    b.HasOne("SipintarBeltim.Models.ForumArahan", "ForumArahan")
                        .WithMany("TindakLanjuts")
                        .HasForeignKey("ForumArahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumArahan");
                });

            modelBuilder.Entity("SipintarBeltim.Models.MatriksRisiko", b =>
                {
                    b.HasOne("SipintarBeltim.Models.LevelDampak", "Dampak")
                        .WithMany()
                        .HasForeignKey("DampakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SipintarBeltim.Models.LevelKemungkinan", "Kemungkinan")
                        .WithMany()
                        .HasForeignKey("KemungkinanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SipintarBeltim.Models.LevelRisiko", "LevelRisiko")
                        .WithMany()
                        .HasForeignKey("LevelRisikoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dampak");

                    b.Navigation("Kemungkinan");

                    b.Navigation("LevelRisiko");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Menu", b =>
                {
                    b.HasOne("SipintarBeltim.Models.Modul", "Modul")
                        .WithMany("Menus")
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SipintarBeltim.Models.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Modul");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SipintarBeltim.Models.RolePermission", b =>
                {
                    b.HasOne("SipintarBeltim.Models.Menu", "Menu")
                        .WithMany("RolePermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SipintarBeltim.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SipintarBeltim.Models.User", b =>
                {
                    b.HasOne("SipintarBeltim.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Wilayah", b =>
                {
                    b.HasOne("SipintarBeltim.Models.Wilayah", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumArahan", b =>
                {
                    b.Navigation("TindakLanjuts");
                });

            modelBuilder.Entity("SipintarBeltim.Models.ForumTopik", b =>
                {
                    b.Navigation("Komentars");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Modul", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SipintarBeltim.Models.Wilayah", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
